name:                todoCli
version:             0.1.0.0
github:              "githubuser/todoCli"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/todoCli#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- unordered-containers
- generic-lens
- regex-tdfa
- containers
- microlens
- hashable
- text
- time
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
  - ImportQualifiedPost
  - OverloadedStrings
  - OverloadedLists
  - BlockArguments
  - TupleSections
  - BangPatterns
  - LambdaCase
  - DuplicateRecordFields
  - OverloadedRecordDot
  - OverloadedLabels
  - NoFieldSelectors
  - RecordWildCards
  - NamedFieldPuns
  - FlexibleContexts
  - TypeApplications
  - DeriveGeneric
  - DataKinds
  - DeriveAnyClass

executables:
  todoCli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todoCli
    default-extensions:
    - ImportQualifiedPost
    - OverloadedStrings
    - OverloadedLists
    - BlockArguments
    - TupleSections
    - BangPatterns
    - LambdaCase
    - DuplicateRecordFields
    - OverloadedRecordDot
    - OverloadedLabels
    - NoFieldSelectors
    - RecordWildCards
    - NamedFieldPuns
    - FlexibleContexts
    - TypeApplications
    - DeriveGeneric
    - DataKinds
    - DeriveAnyClass

tests:
  todoCli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todoCli
