author: SUHYEON CHOI
copyright: "2025 SUHYEON CHOI (1AzyF0x)"
data-files:
  - docs/long-help.txt
  - docs/todo.1
dependencies:
  - base
  - bytestring
  - cereal
  - containers
  - data-interval
  - directory
  - file-embed
  - filepath
  - formatting
  - hashable
  - mtl
  - optparse-applicative
  - regex-tdfa
  - split
  - table-layout
  - template-haskell
  - text
  - time
  - tomland
  - transformers
  - unordered-containers
  - vty
  - witch
description: "Please see the README on GitHub at <https://github.com/Choi-Suhyeon/todoCli#readme>"
executables:
  todo:
    default-extensions:
      - FlexibleContexts
      - FlexibleInstances
      - MultiParamTypeClasses
      - FunctionalDependencies
      - ConstraintKinds
      - ScopedTypeVariables
      - DataKinds
      - TypeApplications
      - DeriveGeneric
      - DeriveAnyClass
      - GeneralizedNewtypeDeriving
      - DerivingStrategies
      - StandaloneDeriving
      - DerivingVia
      - OverloadedStrings
      - OverloadedLists
      - DuplicateRecordFields
      - OverloadedRecordDot
      - OverloadedLabels
      - NoFieldSelectors
      - RecordWildCards
      - NamedFieldPuns
      - ImportQualifiedPost
      - NoImplicitPrelude
      - PackageImports
      - BlockArguments
      - TupleSections
      - LambdaCase
      - MultiWayIf
      - BangPatterns
      - NumericUnderscores
    dependencies:
      - todo
    ghc-options:
      - "-threaded"
      - "-rtsopts"
      - "-with-rtsopts=-N"
    main: Main.hs
    source-dirs: app
extra-source-files:
  - README.md
  - CHANGELOG.md
  - ROADMAP.md
  - docs/long-help.md
ghc-options:
  - "-Wall"
  - "-Wcompat"
  - "-Widentities"
  - "-Wincomplete-record-updates"
  - "-Wincomplete-uni-patterns"
  - "-Wmissing-export-lists"
  - "-Wmissing-home-modules"
  - "-Wredundant-constraints"
github: Choi-Suhyeon/todoCli
library:
  default-extensions:
    - FlexibleContexts
    - FlexibleInstances
    - MultiParamTypeClasses
    - FunctionalDependencies
    - ConstraintKinds
    - ScopedTypeVariables
    - DataKinds
    - TypeApplications
    - DeriveGeneric
    - DeriveAnyClass
    - GeneralizedNewtypeDeriving
    - DerivingStrategies
    - StandaloneDeriving
    - DerivingVia
    - OverloadedStrings
    - OverloadedLists
    - DuplicateRecordFields
    - OverloadedRecordDot
    - OverloadedLabels
    - NoFieldSelectors
    - RecordWildCards
    - NamedFieldPuns
    - ImportQualifiedPost
    - NoImplicitPrelude
    - PackageImports
    - BlockArguments
    - TupleSections
    - LambdaCase
    - MultiWayIf
    - BangPatterns
    - NumericUnderscores
  source-dirs: src
license: BSD-3-Clause
maintainer: "SUHYEON CHOI (1AzyF0x) <1AzyF0x@protonmail.ch>"
name: todo
version: '2.1.0'
